languageCode = "en"
languageName = "English"
weight = 1
title = "Security Jungle - Data Backup Solutions"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "/img/dc_logo.png"
  description = "We solve technical problems, with a smile!"

[params.author]
  name = "Joshua Fraze"
  email = "josh@securityjungle.com"
  image = "/img/joshfraze.jpg"
  headline = "Data Backup Expert"
  bio = "I protect your data!"
  links = [
    { "linkedin" = "https://linkedin.com/in/securityjungle" },
    { "twitter" = "https://twitter.com/securityjungle" },
    { "instagram" = "https://instagram.com/securityjungle" },
    { "github" = "https://github.com/securityjungle" }
  ]
